- name: hotpotqa_agent
  _target_: recipe.hotpotqa.hotpotqa_agent_flow.HotpotQAAgentFlow
  max_steps: 5
  max_parallel_calls: 4

  embedding_model_name: BAAI/bge-large-en-v1.5
  embedding_devices: null
